### ISSUE TITLE
Update cluFlock?

### ISSUE THREAD

**Issue by denisandroid** [Larusso/unity-version-manager#59]
https://github.com/Larusso/unity-version-manager/blob/master/uvm_core/Cargo.toml

```
[target.'cfg(unix)'.dependencies]
cluFlock = "=0.1.5"
```

Were you considering upgrading the library version to "1.2.5"? Added support for Windows platform.

Or are there problems that don 't make it possible?

https://crates.io/crates/cluFlock

**Comment by Larusso** [comment]
I never much considered to use file locking on windows because they are locked by the OS normally (depending how you open the file). If There is a native windows support I don't see a reason not to use it though. But I need to check what changes this requires. I think I created a helper macro around it.

**Comment by Larusso** [comment]
Ah now I remember. I had to pin `cluFlock` because of a breaking change. I need to revisit this.

**Comment by denisandroid** [comment]
MMM, everything is normal?

**Comment by Larusso** [comment]
```
| use cluFlock::{ExclusiveSliceLock, Flock};
|                ^^^^^^^^^^^^^^^^^^  ^^^^^ no `Flock` in the root
|                |
|                no `ExclusiveSliceLock` in the root
|                help: a similar name exists in the module: `ExclusiveFlock`
```

I had no time last time I encountered this issue.

**Comment by denisandroid** [comment]
Yes, it was a very long time ago)

Now there are no such things like 'ExclusiveLock, ExclusiveSliceLock, SharedLock, SharedSliceLock' everything is simplified.

```
Lock, FlockLock<File>
SliceLock, in your example FlockLock< & File >
```

I think the official examples will help you better than I will on your fingers explain.

**Comment by Larusso** [comment]
@denisandroid I had a few minutes and integrated the latest version. see #69
To activate it for windows I need a few more minutes ;). Some initial tests worked out well but I have other tasks for this project lining up as well.

Thanks for your issue! Your new API makes a lot more sense now. With this I can plan to remove my helper functions and macros I created to have a one-line lock function.

**Comment by denisandroid** [comment]
I think it went well, close the issue?

**Comment by Larusso** [comment]
Will do with the merge.
